# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: auth0-custom-lock-push
env:
  NODE_ENV: 'development'
  nodeVersion: '14.x'

on:
  push:
    branches:
      - master

jobs:
  dev-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.nodeVersion }}
    - run: npm ci
    - run: npm run build
